import type { Locale } from '@/lib/i18n/config';
import type { SiteContent } from '@/types';

const P = '/media/photos';
const C = '/media/certificates';

/**
 * Контент-как-код. Данные отделены от презентации (см. docs/architecture.md).
 * ВНИМАНИЕ: цифры, проекты и сертификаты — ВРЕМЕННЫЕ плейсхолдеры (см. decisions D7),
 * заменяются реальными материалами заказчика. Ничего не выдаём за реальные достижения.
 */
const ru: SiteContent = {
  company: {
    name: 'АРКОН',
    legalName: 'ООО «АРКОН»',
    inn: '1231231231',
    kpp: '321213123',
    tagline: 'Инженерно-строительная компания полного цикла',
    foundedNote: 'Проектирование · строительство · реконструкция · сопровождение',
  },
  nav: [
    { label: 'Компания', href: '#about' },
    { label: 'Услуги', href: '#services' },
    { label: 'Отрасли', href: '#sectors' },
    { label: 'Проекты', href: '#projects' },
    { label: 'Качество', href: '#quality' },
    { label: 'Контакты', href: '#contact' },
  ],
  hero: {
    kicker: 'EPC · Полный цикл',
    title: 'Сложные инженерные объекты — от проекта до ввода в эксплуатацию',
    subtitle:
      'Проектируем, строим и реконструируем инженерные сети, здания, дороги, портовые и гидротехнические сооружения. Берём объект целиком и отвечаем за результат.',
    ctaPrimary: 'Обсудить проект',
    ctaSecondary: 'Смотреть проекты',
    marquee: [
      'Инженерные сети',
      'Гидротехника',
      'Портовые сооружения',
      'Дорожная инфраструктура',
      'Промышленные объекты',
      'Дноуглубление',
    ],
  },
  stats: [
    { value: '18', label: 'лет на рынке', note: 'опыт полного цикла' },
    { value: '240+', label: 'реализованных объектов', note: 'по РФ' },
    { value: '1 400', label: 'км инженерных сетей', note: 'построено и реконструировано' },
    { value: '32', label: 'региона', note: 'география работ' },
  ],
  about: {
    kicker: 'О компании',
    title: 'Инженерная ответственность за объект целиком',
    lead:
      'АРКОН — инженерно-строительная компания полного цикла. Мы закрываем весь путь объекта: изыскания, проектирование, строительство, реконструкцию и инженерное сопровождение.',
    body: [
      'Собственные проектные и производственные подразделения, парк техники и аттестованные специалисты позволяют вести технически сложные объекты без дробления ответственности между подрядчиками.',
      'Работаем с государственными и частными заказчиками, инвесторами и девелоперами — от отдельных инженерных систем до комплексных объектов инфраструктуры под ключ.',
    ],
  },
  fullCycle: {
    kicker: 'Полный цикл',
    title: 'Один подрядчик на всех этапах',
    intro: 'Единая ответственность исключает разрывы между проектом, стройкой и эксплуатацией.',
    steps: [
      { no: '01', title: 'Изыскания и проект', description: 'Инженерные изыскания, проектирование, экспертиза и согласования.' },
      { no: '02', title: 'Строительство', description: 'Генподряд, СМР, инженерные сети, специальные и подводные работы.' },
      { no: '03', title: 'Реконструкция', description: 'Модернизация и восстановление действующих объектов и сетей.' },
      { no: '04', title: 'Сопровождение', description: 'Стройконтроль, авторский надзор, функции заказчика-застройщика.' },
    ],
  },
  services: {
    kicker: 'Услуги',
    title: 'Четыре направления полного цикла',
    intro: 'Каждое направление — самостоятельная компетенция с собственной командой и техникой.',
    items: [
      {
        no: '01',
        slug: 'design',
        title: 'Проектирование',
        summary: 'Инженерные изыскания и проектная документация для объектов любой сложности.',
        points: ['Проектирование зданий', 'Проектирование инженерных сетей', 'Гидротехнические сооружения', 'Транспортная инфраструктура', 'BIM-моделирование', 'Рабочая документация'],
        image: `${P}/service-design.jpg`,
      },
      {
        no: '02',
        slug: 'construction',
        title: 'Строительство',
        summary: 'Генподряд и строительно-монтажные работы с собственными ресурсами.',
        points: ['Генеральный подряд', 'Общестроительные работы', 'Инженерные сети', 'Дорожное строительство', 'Коммунальная инфраструктура', 'Портовые и гидротехнические сооружения'],
        image: `${P}/service-construction.jpg`,
      },
      {
        no: '03',
        slug: 'reconstruction',
        title: 'Реконструкция',
        summary: 'Модернизация действующих объектов без остановки эксплуатации.',
        points: ['Реконструкция зданий', 'Модернизация инженерных сетей', 'Реконструкция инфраструктуры', 'Усиление конструкций', 'Капитальный ремонт'],
        image: `${P}/service-reconstruction.jpg`,
      },
      {
        no: '04',
        slug: 'supervision',
        title: 'Инженерное сопровождение',
        summary: 'Контроль качества и сроков на всём протяжении реализации.',
        points: ['Строительный контроль', 'Авторский надзор', 'Технический надзор', 'Управление строительством', 'Контроль качества', 'Технический аудит'],
        image: `${P}/service-supervision.jpg`,
      },
    ],
  },
  sectors: {
    kicker: 'Отрасли и объекты',
    title: 'Где мы работаем',
    intro: 'Компетенции в инфраструктуре, гидротехнике и промышленном строительстве.',
    items: [
      { slug: 'networks', title: 'Инженерные сети', image: `${P}/sector-networks.jpg` },
      { slug: 'buildings', title: 'Здания и сооружения', image: `${P}/sector-buildings.jpg` },
      { slug: 'roads', title: 'Дорожная инфраструктура', image: `${P}/sector-roads.jpg` },
      { slug: 'utilities', title: 'Коммунальная инфраструктура', image: `${P}/sector-utilities.jpg` },
      { slug: 'port', title: 'Портовые сооружения', image: `${P}/sector-port.jpg` },
      { slug: 'hydro', title: 'Гидротехнические объекты', image: `${P}/sector-hydro.jpg` },
      { slug: 'industrial', title: 'Промышленные объекты', image: `${P}/sector-industrial.jpg` },
      { slug: 'urban', title: 'Городская инфраструктура', image: `${P}/sector-urban.jpg` },
    ],
  },
  expertise: {
    kicker: 'Компетенции',
    title: 'Почему объект можно доверить целиком',
    intro: 'Ресурсы и процессы, за которыми стоит инженерная культура, а не обещания.',
    items: [
      { title: 'Инженерное проектирование', description: 'Проектный офис в штате — от изысканий до рабочей документации, сквозная передача решений на площадку.' },
      { title: 'Инфраструктурное строительство', description: 'Инженерные сети, дороги, коммунальные, портовые и гидротехнические объекты собственными ресурсами.' },
      { title: 'BIM · информационное моделирование', description: 'Единая цифровая модель, сбор коллизий и увязка инженерных систем на этапе проектирования.' },
      { title: 'Управление проектами', description: 'Единый график, прозрачная отчётность и контроль бюджета на всех этапах реализации.' },
      { title: 'Система контроля качества', description: 'Входной и операционный контроль материалов и работ, исполнительная документация.' },
      { title: 'Охрана труда и безопасность (HSE)', description: 'Обученные бригады, наряды-допуски, регулярный аудит площадок.' },
      { title: 'Технический контроль', description: 'Строительный контроль, авторский и технический надзор, функции заказчика-застройщика.' },
      { title: 'Реконструкция сложных объектов', description: 'Диагностика, усиление конструкций и модернизация действующих объектов без остановки эксплуатации.' },
    ],
  },
  projects: {
    kicker: 'Проекты',
    title: 'Избранные объекты',
    intro: 'Примеры задач полного цикла — от инженерных сетей до гидротехники.',
    cta: 'Все проекты',
    items: [
      {
        slug: 'port-hydro',
        title: 'Реконструкция причального комплекса',
        sector: 'Портовые сооружения',
        location: 'Северо-Запад РФ',
        year: '2024',
        scope: 'Проект · Строительство · Дноуглубление',
        image: `${P}/project-1.jpg`,
        facts: [
          { label: 'Длина причала', value: '420 м' },
          { label: 'Объём дноуглубления', value: '180 000 м³' },
          { label: 'Срок', value: '14 мес.' },
        ],
      },
      {
        slug: 'water-networks',
        title: 'Магистральные сети водоснабжения',
        sector: 'Инженерные сети',
        location: 'Ленинградская область',
        year: '2023',
        scope: 'Проект · Строительство',
        image: `${P}/project-2.jpg`,
        facts: [
          { label: 'Протяжённость', value: '46 км' },
          { label: 'Диаметр', value: 'до 1000 мм' },
          { label: 'Срок', value: '11 мес.' },
        ],
      },
      {
        slug: 'industrial-plant',
        title: 'Инженерная инфраструктура промышленного объекта',
        sector: 'Промышленные объекты',
        location: 'Центральный ФО',
        year: '2022',
        scope: 'Проект · Строительство · Сопровождение',
        image: `${P}/project-3.jpg`,
        facts: [
          { label: 'Площадь', value: '12 га' },
          { label: 'Сети', value: '6 видов' },
          { label: 'Срок', value: '18 мес.' },
        ],
      },
    ],
  },
  quality: {
    kicker: 'Качество · HSE',
    title: 'Безопасность и качество на площадке',
    intro: 'Инженерный объект — это в первую очередь предсказуемость и отсутствие происшествий.',
    pillars: [
      { title: 'Система менеджмента качества', description: 'Процедуры контроля на каждом этапе, входной и операционный контроль материалов и работ.' },
      { title: 'Охрана труда и промбезопасность', description: 'Обученные бригады, наряды-допуски, регулярный аудит площадок.' },
      { title: 'Экологическая ответственность', description: 'Проектные решения и производство работ с учётом экологических требований.' },
      { title: 'Соблюдение сроков', description: 'Планирование ресурсов и резервирование под критический путь графика.' },
    ],
  },
  certifications: {
    kicker: 'Сертификаты и допуски',
    title: 'Разрешительная база',
    intro: 'Членство в СРО, системы менеджмента и аттестации специалистов.',
    disclaimer: 'Показаны образцы оформления. Реальные документы будут размещены после предоставления заказчиком.',
    items: [
      { title: 'Свидетельство СРО', issuer: 'Саморегулируемая организация', no: 'Образец', image: `${C}/cert-sro.svg`, placeholder: true },
      { title: 'ISO 9001', issuer: 'Менеджмент качества', no: 'Образец', image: `${C}/cert-iso9001.svg`, placeholder: true },
      { title: 'ISO 14001', issuer: 'Экологический менеджмент', no: 'Образец', image: `${C}/cert-iso14001.svg`, placeholder: true },
      { title: 'ISO 45001', issuer: 'Охрана труда', no: 'Образец', image: `${C}/cert-iso45001.svg`, placeholder: true },
    ],
  },
  partners: {
    kicker: 'Партнёры и заказчики',
    title: 'С кем мы работаем',
    intro: 'Государственные и коммерческие заказчики, инвесторы и девелоперы — от отдельных систем до объектов инфраструктуры под ключ.',
    note: 'Логотипы — образцы оформления. Реальные логотипы заказчиков размещаются только с их разрешения.',
    items: [
      { name: 'Государственный заказчик', kind: 'Госсектор' },
      { name: 'Муниципальная структура', kind: 'Госсектор' },
      { name: 'Промышленный холдинг', kind: 'Промышленность' },
      { name: 'Портовый оператор', kind: 'Инфраструктура' },
      { name: 'Девелопер', kind: 'Строительство' },
      { name: 'Инвестиционный фонд', kind: 'Инвестор' },
    ],
  },
  geography: {
    kicker: 'География',
    title: 'Работаем по всей стране',
    intro: 'Мобильные подразделения и логистика позволяют вести объекты в разных регионах.',
    regions: ['Северо-Запад', 'Центральный ФО', 'Поволжье', 'Юг России', 'Урал', 'Сибирь', 'Дальний Восток', 'Арктическая зона'],
  },
  news: {
    kicker: 'Новости',
    title: 'Пресс-центр',
    cta: 'Все новости',
    items: [
      { slug: 'news-1', date: '12.06.2026', category: 'Проекты', title: 'Завершён этап реконструкции причального комплекса', excerpt: 'Сдан ключевой этап работ с опережением графика.', image: `${P}/news-1.jpg` },
      { slug: 'news-2', date: '28.04.2026', category: 'Компания', title: 'Расширен парк специальной техники', excerpt: 'Инвестиции в оборудование для гидротехнических работ.', image: `${P}/news-2.jpg` },
      { slug: 'news-3', date: '15.03.2026', category: 'Технологии', title: 'Внедрение BIM на объектах инженерных сетей', excerpt: 'Единая модель ускоряет согласования и снижает риски.', image: `${P}/news-3.jpg` },
    ],
  },
  contact: {
    kicker: 'Контакты',
    title: 'Обсудим ваш объект',
    intro: 'Опишите задачу — инженер свяжется с вами и предложит решение полного цикла.',
    form: {
      name: 'Имя',
      company: 'Компания',
      email: 'E-mail',
      phone: 'Телефон',
      message: 'Кратко о задаче',
      submit: 'Отправить запрос',
      consent: 'Отправляя форму, я соглашаюсь на обработку персональных данных в соответствии с 152-ФЗ и принимаю',
    },
  },
  footer: {
    about: 'Инженерно-строительная компания полного цикла: проектирование, строительство, реконструкция и сопровождение инженерных объектов.',
    columns: [
      { title: 'Компания', links: [{ label: 'О компании', href: '#about' }, { label: 'Компетенции', href: '#expertise' }, { label: 'Качество · HSE', href: '#quality' }, { label: 'Партнёры', href: '#partners' }, { label: 'Новости', href: '/news' }] },
      { title: 'Направления', links: [{ label: 'Проектирование', href: '/services/design' }, { label: 'Строительство', href: '/services/construction' }, { label: 'Реконструкция', href: '/services/reconstruction' }, { label: 'Сопровождение', href: '/services/supervision' }] },
      { title: 'Отрасли', links: [{ label: 'Инженерные сети', href: '#sectors' }, { label: 'Гидротехника', href: '#sectors' }, { label: 'Портовые сооружения', href: '#sectors' }, { label: 'Промышленные объекты', href: '#sectors' }] },
    ],
    rights: 'Все права защищены.',
    placeholderNote: 'Демонстрационная версия. Фотографии и сертификаты — временные материалы из свободных источников, заменяются реальными данными заказчика.',
  },
  common: {
    menu: 'Меню',
    close: 'Закрыть',
    requestQuote: 'Обсудить проект',
    learnMore: 'Подробнее',
    allProjects: 'Все проекты',
    scroll: 'Листайте вниз',
    sampleBadge: 'Образец',
  },
  ui: {
    home: 'Главная',
    backHome: 'На главную',
    servicesTitle: 'Услуги',
    servicesLead: 'Четыре направления полного цикла — от изысканий и проекта до строительства и сопровождения.',
    projectsTitle: 'Проекты',
    projectsLead: 'Избранные объекты полного цикла — инженерные сети, гидротехника, промышленная инфраструктура.',
    newsTitle: 'Пресс-центр',
    newsLead: 'Новости компании, проектов и технологий.',
    whatWeDeliver: 'Что входит в работы',
    howWeWork: 'Как мы работаем',
    task: 'Задача',
    result: 'Результат',
    gallery: 'Галерея',
    facts: 'Ключевые факты',
    otherServices: 'Другие направления',
    otherProjects: 'Другие проекты',
    otherNews: 'Другие новости',
    readMore: 'Читать',
    ctaTitle: 'Обсудим ваш объект?',
    ctaText: 'Опишите задачу — инженер предложит решение полного цикла.',
    privacyPolicy: 'Политика конфиденциальности',
  },
};

const en: SiteContent = {
  company: {
    name: 'ARCON',
    legalName: 'ARCON LLC',
    inn: '1231231231',
    kpp: '321213123',
    tagline: 'Full-cycle engineering and construction company',
    foundedNote: 'Design · construction · reconstruction · supervision',
  },
  nav: [
    { label: 'Company', href: '#about' },
    { label: 'Services', href: '#services' },
    { label: 'Sectors', href: '#sectors' },
    { label: 'Projects', href: '#projects' },
    { label: 'Quality', href: '#quality' },
    { label: 'Contacts', href: '#contact' },
  ],
  hero: {
    kicker: 'EPC · Full cycle',
    title: 'Complex engineering facilities — from design to commissioning',
    subtitle:
      'We design, build and reconstruct utility networks, buildings, roads, port and hydraulic structures. We take on the whole facility and own the result.',
    ctaPrimary: 'Discuss a project',
    ctaSecondary: 'View projects',
    marquee: [
      'Utility networks',
      'Hydraulic engineering',
      'Port structures',
      'Road infrastructure',
      'Industrial facilities',
      'Dredging',
    ],
  },
  stats: [
    { value: '18', label: 'years on the market', note: 'full-cycle experience' },
    { value: '240+', label: 'completed facilities', note: 'across Russia' },
    { value: '1,400', label: 'km of utility networks', note: 'built and reconstructed' },
    { value: '32', label: 'regions', note: 'geography of works' },
  ],
  about: {
    kicker: 'Company',
    title: 'Engineering accountability for the entire facility',
    lead:
      'ARCON is a full-cycle engineering and construction company. We cover the entire lifecycle of a facility: surveys, design, construction, reconstruction and engineering supervision.',
    body: [
      'In-house design and production units, an equipment fleet and certified specialists let us deliver technically complex facilities without splitting responsibility across contractors.',
      'We work with public and private clients, investors and developers — from individual utility systems to turnkey infrastructure projects.',
    ],
  },
  fullCycle: {
    kicker: 'Full cycle',
    title: 'One contractor across every stage',
    intro: 'Single accountability removes the gaps between design, construction and operation.',
    steps: [
      { no: '01', title: 'Surveys & design', description: 'Engineering surveys, design, expert review and approvals.' },
      { no: '02', title: 'Construction', description: 'General contracting, civil works, utilities, special and underwater works.' },
      { no: '03', title: 'Reconstruction', description: 'Modernisation and restoration of existing facilities and networks.' },
      { no: '04', title: 'Supervision', description: 'Construction control, designer supervision, client-developer functions.' },
    ],
  },
  services: {
    kicker: 'Services',
    title: 'Four full-cycle disciplines',
    intro: 'Each discipline is a standalone competence with its own team and equipment.',
    items: [
      { no: '01', slug: 'design', title: 'Design', summary: 'Engineering surveys and design documentation for facilities of any complexity.', points: ['Building design', 'Utility network design', 'Hydraulic structures', 'Transport infrastructure', 'BIM modelling', 'Working documentation'], image: `${P}/service-design.jpg` },
      { no: '02', slug: 'construction', title: 'Construction', summary: 'General contracting and civil works with in-house resources.', points: ['General contracting', 'General construction works', 'Utility networks', 'Road construction', 'Municipal infrastructure', 'Port & hydraulic structures'], image: `${P}/service-construction.jpg` },
      { no: '03', slug: 'reconstruction', title: 'Reconstruction', summary: 'Modernisation of operating facilities without halting operation.', points: ['Building reconstruction', 'Utility network modernisation', 'Infrastructure reconstruction', 'Structural reinforcement', 'Capital repair'], image: `${P}/service-reconstruction.jpg` },
      { no: '04', slug: 'supervision', title: 'Engineering supervision', summary: 'Quality and schedule control throughout delivery.', points: ['Construction control', 'Designer supervision', 'Technical supervision', 'Construction management', 'Quality control', 'Technical audit'], image: `${P}/service-supervision.jpg` },
    ],
  },
  sectors: {
    kicker: 'Sectors & facilities',
    title: 'Where we work',
    intro: 'Expertise across infrastructure, hydraulic engineering and industrial construction.',
    items: [
      { slug: 'networks', title: 'Utility networks', image: `${P}/sector-networks.jpg` },
      { slug: 'buildings', title: 'Buildings & structures', image: `${P}/sector-buildings.jpg` },
      { slug: 'roads', title: 'Road infrastructure', image: `${P}/sector-roads.jpg` },
      { slug: 'utilities', title: 'Municipal infrastructure', image: `${P}/sector-utilities.jpg` },
      { slug: 'port', title: 'Port structures', image: `${P}/sector-port.jpg` },
      { slug: 'hydro', title: 'Hydraulic facilities', image: `${P}/sector-hydro.jpg` },
      { slug: 'industrial', title: 'Industrial facilities', image: `${P}/sector-industrial.jpg` },
      { slug: 'urban', title: 'Urban infrastructure', image: `${P}/sector-urban.jpg` },
    ],
  },
  expertise: {
    kicker: 'Expertise',
    title: 'Why the whole facility can be entrusted to us',
    intro: 'Resources and processes backed by engineering culture, not promises.',
    items: [
      { title: 'Engineering design', description: 'In-house design office — from surveys to working documentation, seamless handover to site.' },
      { title: 'Infrastructure construction', description: 'Utility networks, roads, municipal, port and hydraulic facilities with in-house resources.' },
      { title: 'BIM · information modelling', description: 'A single digital model, clash detection and coordination of engineering systems at design stage.' },
      { title: 'Project management', description: 'A single schedule, transparent reporting and budget control at every stage.' },
      { title: 'Quality control system', description: 'Incoming and in-process inspection of materials and works, as-built documentation.' },
      { title: 'Occupational safety (HSE)', description: 'Trained crews, work permits, regular site audits.' },
      { title: 'Technical supervision', description: 'Construction control, designer and technical supervision, client-developer functions.' },
      { title: 'Reconstruction of complex facilities', description: 'Diagnostics, structural reinforcement and modernisation of operating facilities without halting operation.' },
    ],
  },
  projects: {
    kicker: 'Projects',
    title: 'Selected facilities',
    intro: 'Examples of full-cycle work — from utility networks to hydraulic engineering.',
    cta: 'All projects',
    items: [
      { slug: 'port-hydro', title: 'Berth complex reconstruction', sector: 'Port structures', location: 'North-West Russia', year: '2024', scope: 'Design · Construction · Dredging', image: `${P}/project-1.jpg`, facts: [{ label: 'Berth length', value: '420 m' }, { label: 'Dredging volume', value: '180,000 m³' }, { label: 'Duration', value: '14 mo.' }] },
      { slug: 'water-networks', title: 'Trunk water supply networks', sector: 'Utility networks', location: 'Leningrad Region', year: '2023', scope: 'Design · Construction', image: `${P}/project-2.jpg`, facts: [{ label: 'Length', value: '46 km' }, { label: 'Diameter', value: 'up to 1000 mm' }, { label: 'Duration', value: '11 mo.' }] },
      { slug: 'industrial-plant', title: 'Industrial facility engineering infrastructure', sector: 'Industrial facilities', location: 'Central Russia', year: '2022', scope: 'Design · Construction · Supervision', image: `${P}/project-3.jpg`, facts: [{ label: 'Area', value: '12 ha' }, { label: 'Networks', value: '6 types' }, { label: 'Duration', value: '18 mo.' }] },
    ],
  },
  quality: {
    kicker: 'Quality · HSE',
    title: 'Safety and quality on site',
    intro: 'An engineering facility is, above all, predictability and zero incidents.',
    pillars: [
      { title: 'Quality management system', description: 'Control procedures at every stage, incoming and in-process inspection of materials and works.' },
      { title: 'Occupational & industrial safety', description: 'Trained crews, work permits, regular site audits.' },
      { title: 'Environmental responsibility', description: 'Design decisions and works executed to environmental requirements.' },
      { title: 'On-time delivery', description: 'Resource planning and buffers on the schedule critical path.' },
    ],
  },
  certifications: {
    kicker: 'Certificates & permits',
    title: 'Permits and accreditations',
    intro: 'SRO membership, management systems and specialist certifications.',
    disclaimer: 'Layout samples are shown. Real documents will be published once provided by the client.',
    items: [
      { title: 'SRO certificate', issuer: 'Self-regulatory organisation', no: 'Sample', image: `${C}/cert-sro.svg`, placeholder: true },
      { title: 'ISO 9001', issuer: 'Quality management', no: 'Sample', image: `${C}/cert-iso9001.svg`, placeholder: true },
      { title: 'ISO 14001', issuer: 'Environmental management', no: 'Sample', image: `${C}/cert-iso14001.svg`, placeholder: true },
      { title: 'ISO 45001', issuer: 'Occupational health & safety', no: 'Sample', image: `${C}/cert-iso45001.svg`, placeholder: true },
    ],
  },
  partners: {
    kicker: 'Partners & clients',
    title: 'Who we work with',
    intro: 'Public and private clients, investors and developers — from individual systems to turnkey infrastructure.',
    note: 'Logos are layout samples. Real client logos are used only with their permission.',
    items: [
      { name: 'Public client', kind: 'Public sector' },
      { name: 'Municipal authority', kind: 'Public sector' },
      { name: 'Industrial holding', kind: 'Industry' },
      { name: 'Port operator', kind: 'Infrastructure' },
      { name: 'Developer', kind: 'Construction' },
      { name: 'Investment fund', kind: 'Investor' },
    ],
  },
  geography: {
    kicker: 'Geography',
    title: 'Working nationwide',
    intro: 'Mobile units and logistics let us deliver facilities across regions.',
    regions: ['North-West', 'Central', 'Volga', 'South', 'Urals', 'Siberia', 'Far East', 'Arctic zone'],
  },
  news: {
    kicker: 'News',
    title: 'Press centre',
    cta: 'All news',
    items: [
      { slug: 'news-1', date: '12.06.2026', category: 'Projects', title: 'Berth complex reconstruction milestone completed', excerpt: 'A key stage delivered ahead of schedule.', image: `${P}/news-1.jpg` },
      { slug: 'news-2', date: '28.04.2026', category: 'Company', title: 'Special equipment fleet expanded', excerpt: 'Investment in equipment for hydraulic works.', image: `${P}/news-2.jpg` },
      { slug: 'news-3', date: '15.03.2026', category: 'Technology', title: 'BIM adoption on utility network projects', excerpt: 'A single model speeds up approvals and reduces risk.', image: `${P}/news-3.jpg` },
    ],
  },
  contact: {
    kicker: 'Contacts',
    title: 'Let’s discuss your facility',
    intro: 'Describe the task — an engineer will get in touch and propose a full-cycle solution.',
    form: {
      name: 'Name',
      company: 'Company',
      email: 'E-mail',
      phone: 'Phone',
      message: 'Briefly about the task',
      submit: 'Send request',
      consent: 'By submitting the form, I consent to the processing of personal data and accept the',
    },
  },
  footer: {
    about: 'A full-cycle engineering and construction company: design, construction, reconstruction and supervision of engineering facilities.',
    columns: [
      { title: 'Company', links: [{ label: 'About', href: '#about' }, { label: 'Expertise', href: '#expertise' }, { label: 'Quality · HSE', href: '#quality' }, { label: 'Partners', href: '#partners' }, { label: 'News', href: '/news' }] },
      { title: 'Services', links: [{ label: 'Design', href: '/services/design' }, { label: 'Construction', href: '/services/construction' }, { label: 'Reconstruction', href: '/services/reconstruction' }, { label: 'Supervision', href: '/services/supervision' }] },
      { title: 'Sectors', links: [{ label: 'Utility networks', href: '#sectors' }, { label: 'Hydraulic engineering', href: '#sectors' }, { label: 'Port structures', href: '#sectors' }, { label: 'Industrial facilities', href: '#sectors' }] },
    ],
    rights: 'All rights reserved.',
    placeholderNote: 'Demonstration version. Photos and certificates are temporary materials from free sources, to be replaced with the client’s real data.',
  },
  common: {
    menu: 'Menu',
    close: 'Close',
    requestQuote: 'Discuss a project',
    learnMore: 'Learn more',
    allProjects: 'All projects',
    scroll: 'Scroll down',
    sampleBadge: 'Sample',
  },
  ui: {
    home: 'Home',
    backHome: 'Back to home',
    servicesTitle: 'Services',
    servicesLead: 'Four full-cycle disciplines — from surveys and design to construction and supervision.',
    projectsTitle: 'Projects',
    projectsLead: 'Selected full-cycle facilities — utility networks, hydraulic engineering, industrial infrastructure.',
    newsTitle: 'Press centre',
    newsLead: 'Company, project and technology news.',
    whatWeDeliver: 'What the works include',
    howWeWork: 'How we work',
    task: 'Task',
    result: 'Result',
    gallery: 'Gallery',
    facts: 'Key facts',
    otherServices: 'Other services',
    otherProjects: 'Other projects',
    otherNews: 'Other news',
    readMore: 'Read',
    ctaTitle: 'Shall we discuss your facility?',
    ctaText: 'Describe the task — an engineer will propose a full-cycle solution.',
    privacyPolicy: 'Privacy Policy',
  },
};

const content: Record<Locale, SiteContent> = { ru, en };

export function getContent(locale: Locale): SiteContent {
  return content[locale] ?? content.ru;
}
